# Configuration file for generating SUMO network with bus stops and routes

[network]
grid_size = 5
edge_length = 100
intersection_control = "traffic_light"
no_turnarounds = true
terminus_length = 50
sidewalks = true
output_file = "../networks/grid.net.xml"

[bus_stops]
every_nth = 2
stop_length = 7
stop_position = 50
output_file = "../networks/grid.bus_stops.add.xml"

[routes]
stop_duration = 10
repeat = 20
num_buses = 7
output_file = "../networks/grid.rou.xml"

[sumocfg]
output_file = "../networks/grid.sumocfg"
# leave a trailing newline
